CREATE SCHEMA "triggers";

CREATE SCHEMA "private";
GRANT USAGE ON SCHEMA "private" TO service_role;
GRANT ALL ON ALL TABLES IN SCHEMA "private" TO service_role;
GRANT ALL ON ALL ROUTINES IN SCHEMA "private" TO service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA "private" TO service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA "private" GRANT ALL ON TABLES TO service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA "private" GRANT ALL ON ROUTINES TO service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA "private" GRANT ALL ON SEQUENCES TO service_role;